[tests][libcxx] Move libcxxtest-libcxx_diagnostics_nodiscard_extensions to unsupported
The following test fails under clang-7 debug due to a memory leak.

Start 199: tests/libcxxtest-libcxx_diagnostics_nodiscard_extensions.pass

199: Test command: /home/azureuser/openenclave/build/tests/libcxx/host/libcxx_host "/home/azureuser/openenclave/build/tests/libcxx/enc/libcxxtest-libcxx_diagnostics_nodiscard_extensions.pass_enc"
199: Test timeout computed to be: 10000000
199: === /home/azureuser/openenclave/build/tests/libcxx/host/libcxx_host: /home/azureuser/openenclave/build/tests/libcxx/enc/libcxxtest-libcxx_diagnostics_nodiscard_extensions.pass_enc
199: RUNNING: ../../3rdparty/libcxx/libcxx/test/libcxx/diagnostics/nodiscard_extensions.pass.cpp
199: PASSED: ../../3rdparty/libcxx/libcxx/test/libcxx/diagnostics/nodiscard_extensions.pass.cpp
199: === _dump(): 4 bytes in 1 blocks
199: 4 bytes
199: oe_debug_malloc(): 7f72b01dc0de
199: oe_malloc(): 7f72b01f2afe
199: malloc(): 7f72b01a9eee
199: _Znwm(): 7f72b00564be
199: _ZnwmRKSt9nothrow_t(): 7f72b005662d
199: _ZNSt3__120get_temporary_bufferIiEENS_4pairIPT_lEEl(): 7f72b00106b6
199: main(): 7f72b0010574
199: enc_test(): 7f72b00929fa
199: ecall_enc_test(): 7f72b0010af4
199: _handle_call_enclave_function(): 7f72b01db0ca
199: _handle_ecall(): 7f72b01d9af4
199: __oe_handle_main(): 7f72b01d94b9
199: oe_enter(): 7f72b02020fb
199:
199:
199: 13:29:53:628048 tid(0x7f72c0ddf0c0) (H)[ERROR]:OE_MEMORY_LEAK[../host/sgx/create.c oe_terminate_enclave:731]
199: : ../tests/libcxx/host/host.cpp(290): error: oe_terminate_enclave(): result=31
1/1 Test #199: tests/libcxxtest-libcxx_diagnostics_nodiscard_extensions.pass ...***Failed    0.58 sec

Mark the test as unsupported.

Signed-off-by: Alin Gabriel Serdean <aserdean@ovn.org>
Signed-off-by: Victor Laza <vlaza@cloudbasesolutions.com>
Co-authored-by: Victor Laza vlaza@cloudbasesolutions.com