Add 'other' test enclave which is shared with the same test host
This test doesn't actually do anything, except it currently fails to
build (as expected) with:

```
In file included from ../tests/oeedger8r/host/main.cpp:8:
In file included from tests/oeedger8r/host/other_u.h:9:
tests/oeedger8r/host/other_args.h:43:5: error: redefinition of enumerator 'fcn_id_trusted_call_id_max'
    fcn_id_trusted_call_id_max = OE_ENUM_MAX
    ^
tests/oeedger8r/host/all_args.h:2957:5: note: previous definition is here
    fcn_id_trusted_call_id_max = OE_ENUM_MAX
    ^
In file included from ../tests/oeedger8r/host/main.cpp:8:
In file included from tests/oeedger8r/host/other_u.h:9:
tests/oeedger8r/host/other_args.h:50:5: error: redefinition of enumerator 'fcn_id_untrusted_call_max'
    fcn_id_untrusted_call_max = OE_ENUM_MAX
    ^
tests/oeedger8r/host/all_args.h:3072:5: note: previous definition is here
    fcn_id_untrusted_call_max = OE_ENUM_MAX
    ^
2 errors generated.
```