oesign: fix a build error.
With gcc9, build fails because keyfile argument can be NULL:

    /home/build/openenclave/tools/oesign/main.c: In function ‘oesign’:
    /home/build/openenclave/tools/oesign/main.c:664:13: error: ‘%s’ directive argument is null [-Werror=format-overflow=]
      664 |             Err("Failed to load file: %s", keyfile);
          |             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Fix the build error by checking the value for NULL before using it.

Signed-off-by: Ismo Puustinen <ismo.puustinen@intel.com>